apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spinapp
  name: spinapp
  namespace: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinapp
  template:
    metadata:
      labels:
        app: spinapp
    spec:
      containers:
        - image: docker.io/sathishkr/spinapp:latest
          name: spinapp
          ports:
            - containerPort: 7878

---

apiVersion: v1
kind: Service
metadata:
  name: spinapp
  namespace: spinnaker
  labels:
    name: spinapp
spec:
  ports:
    - port: 7878
      targetPort: 7878
      protocol: TCP
  selector:
    app: spinapp
  type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spinapp
  namespace: spinnaker
spec:
  rules:
  - host: *
    http:
      paths:
      - path: /spinapp
        backend:
          serviceName: spinapp
          servicePort: 7878

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: spingateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spinapp
spec:
  hosts:
    - "*"
  gateways:
    - spingateway
  http:
    - match:
        - uri:
            prefix: /spinapp
      route:
        - destination:
            host: spinapp
